stages:
  - test

.test_template:
  script:
    - python3 --version
    - pip install -e .
    - python3 -m unittest discover -s tests -p "test_*.py" -v

# Matrix for Python Versions 3.9 through 3.14
test-python-versions:
  extends: .test_template
  image: python:${PYTHON_VERSION}-slim
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11", "3.12", "3.13", "3.14"]

# Specific Linux Distros
test-arch:
  extends: .test_template
  image: archlinux:latest
  before_script:
    - pacman -Syu --noconfirm python3 python-pip
    - python3 -m .venv venv
    - source .venv/bin/activate

test-fedora:
  extends: .test_template
  image: fedora:latest
  before_script:
    - dnf install -y python3 python3-pip

test-windows:
  variables:
    PYTHONIOENCODING: "utf-8"
  stage: test
  tags:
    - saas-windows-medium-amd64
  script:
    - python --version
    - pip install -e .
    - python -m unittest discover -s tests -p "test_*.py" -v

# Would add macOS test but I am not paying for that T_T
