name: Build Linux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    container: python:3.12-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: apt-get update && apt-get install -y --no-install-recommends binutils
      - name: Build
        run: |
          python3 --version
          pip install -e .
          pip install pyinstaller
          chmod +x ./build-scripts/build_linux.sh
          ./build-scripts/build_linux.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MicroBridge-linux
          path: dist/MicroBridge/
          if-no-files-found: error
          retention-days: 7